"""Country code to country name mapping for vlr.gg."""

COUNTRIES: dict[str, str] = {
    "af": "Afghanistan",
    "al": "Albania",
    "dz": "Algeria",
    "ao": "Angola",
    "ar": "Argentina",
    "am": "Armenia",
    "au": "Australia",
    "at": "Austria",
    "aw": "Aruba",
    "az": "Azerbaijan",
    "bs": "Bahamas",
    "bh": "Bahrain",
    "bd": "Bangladesh",
    "bb": "Barbados",
    "by": "Belarus",
    "be": "Belgium",
    "bz": "Belize",
    "bj": "Benin",
    "bm": "Bermuda",
    "bt": "Bhutan",
    "bo": "Bolivia",
    "ba": "Bosnia and Herzegovina",
    "bw": "Botswana",
    "br": "Brazil",
    "bn": "Brunei",
    "bg": "Bulgaria",
    "bf": "Burkina Faso",
    "bi": "Burundi",
    "kh": "Cambodia",
    "cm": "Cameroon",
    "ca": "Canada",
    "cv": "Cape Verde",
    "ky": "Cayman Islands",
    "cf": "Central African Republic",
    "cl": "Chile",
    "cn": "China",
    "co": "Colombia",
    "cg": "Congo",
    "ck": "Cook Islands",
    "cr": "Costa Rica",
    "hr": "Croatia",
    "cu": "Cuba",
    "cy": "Cyprus",
    "cz": "Czech Republic",
    "dk": "Denmark",
    "do": "Dominican Republic",
    "ec": "Ecuador",
    "eg": "Egypt",
    "sv": "El Salvador",
    "er": "Eritrea",
    "ee": "Estonia",
    "en": "England",
    "et": "Ethiopia",
    "eu": "European Union",
    "fo": "Faroe Islands",
    "fj": "Fiji",
    "fi": "Finland",
    "fr": "France",
    "pf": "French Polynesia",
    "ga": "Gabon",
    "ge": "Georgia",
    "de": "Germany",
    "gi": "Gibraltar",
    "gr": "Greece",
    "gl": "Greenland",
    "gp": "Guadeloupe",
    "gu": "Guam",
    "gt": "Guatemala",
    "gy": "Guyana",
    "ht": "Haiti",
    "hn": "Honduras",
    "hk": "Hong Kong",
    "hu": "Hungary",
    "is": "Iceland",
    "in": "India",
    "id": "Indonesia",
    "un": "International",
    "iq": "Iraq",
    "ir": "Iran",
    "ie": "Ireland",
    "il": "Israel",
    "it": "Italy",
    "jm": "Jamaica",
    "jp": "Japan",
    "jo": "Jordan",
    "kz": "Kazakhstan",
    "ke": "Kenya",
    "ki": "Kiribati",
    "kw": "Kuwait",
    "kg": "Kyrgyzstan",
    "la": "Laos",
    "lv": "Latvia",
    "lb": "Lebanon",
    "ly": "Libya",
    "lt": "Lithuania",
    "lu": "Luxembourg",
    "mo": "Macau",
    "mk": "North Macedonia",
    "mg": "Madagascar",
    "my": "Malaysia",
    "mv": "Maldives",
    "mt": "Malta",
    "mx": "Mexico",
    "md": "Moldova",
    "mc": "Monaco",
    "mm": "Myanmar",
    "mn": "Mongolia",
    "ms": "Montserrat",
    "ma": "Morocco",
    "mz": "Mozambique",
    "na": "Namibia",
    "nr": "Nauru",
    "np": "Nepal",
    "nl": "Netherlands",
    "an": "Netherlands Antilles",
    "nc": "New Caledonia",
    "nz": "New Zealand",
    "ng": "Nigeria",
    "nf": "Norfolk Island",
    "kp": "North Korea",
    "mp": "Northern Mariana Islands",
    "no": "Norway",
    "om": "Oman",
    "pk": "Pakistan",
    "ps": "Palestine",
    "pa": "Panama",
    "py": "Paraguay",
    "pe": "Peru",
    "pg": "Papua New Guinea",
    "ph": "Philippines",
    "pl": "Poland",
    "pt": "Portugal",
    "pr": "Puerto Rico",
    "qa": "Qatar",
    "ro": "Romania",
    "ru": "Russia",
    "lc": "Saint Lucia",
    "pm": "Saint Pierre and Miquelon",
    "ws": "Samoa",
    "sa": "Saudi Arabia",
    "sx": "Sint Maarten",
    "rs": "Serbia",
    "sl": "Sierra Leone",
    "sg": "Singapore",
    "sk": "Slovakia",
    "si": "Slovenia",
    "sb": "Solomon Islands",
    "so": "Somalia",
    "za": "South Africa",
    "kr": "South Korea",
    "es": "Spain",
    "lk": "Sri Lanka",
    "sd": "Sudan",
    "se": "Sweden",
    "ch": "Switzerland",
    "sy": "Syria",
    "tw": "Taiwan",
    "tz": "Tanzania",
    "th": "Thailand",
    "tb": "Tibet",
    "tg": "Togo",
    "tt": "Trinidad and Tobago",
    "to": "Tonga",
    "tn": "Tunisia",
    "tr": "Turkey",
    "tc": "Turks and Caicos Islands",
    "tv": "Tuvalu",
    "ug": "Uganda",
    "ua": "Ukraine",
    "ae": "United Arab Emirates",
    "gb": "United Kingdom",
    "us": "United States",
    "uy": "Uruguay",
    "uz": "Uzbekistan",
    "va": "Vatican City",
    "ve": "Venezuela",
    "vn": "Vietnam",
    "vg": "British Virgin Islands",
    "vi": "U.S. Virgin Islands",
    "wa": "Wales",
    "ye": "Yemen",
    "zw": "Zimbabwe",
    "ni": "Nicaragua",
    "sn": "Senegal",
    "sr": "Suriname",
    "sc": "Seychelles",
    "ad": "Andorra",
    "me": "Montenegro",
    "m1": "Mars",
}


def get_country_name(code: str) -> str:
    """Look up a country name by its two-letter code.

    Args:
        code: A two-letter country code (e.g., ``"us"``, ``"kr"``).

    Returns:
        str: The full country name, or an empty string if the code is not
            found.

    """
    return COUNTRIES.get(code, "")
